# Generated by Django 2.0.7 on 2019-07-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0002_auto_20190724_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.FileField(blank=True, upload_to='img/fruits'),
        ),
    ]
