# Generated by Django 2.0.7 on 2019-07-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0003_fruit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.FileField(blank=True, upload_to='fruit_app/img/fruits'),
        ),
    ]
