# Generated by Django 2.0.7 on 2019-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0005_auto_20190729_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
