# Generated by Django 2.0.7 on 2019-07-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0007_auto_20190729_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
