# Generated by Django 2.0.7 on 2019-07-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0008_auto_20190729_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='imageurl',
            field=models.TextField(blank=True),
        ),
    ]
